apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: today-me-backend:latest
          imagePullPolicy: Never
          command: ["celery", "-A", "app.core.celery.celery_app", "worker", "--loglevel=info", "--queues=default"]
          envFrom:
            - secretRef:
                name: app-secret
          livenessProbe:
            exec:
              command: ["celery", "-A", "app.core.celery.celery_app", "inspect", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 30
